FROM node:latest as build
RUN mkdir -p /usr/local/share/nginx/src/app
WORKDIR /usr/local/share/nginx/src/app
COPY package.json /usr/local/share/nginx/src/app

RUN npm install
RUN npm install react-scripts@1.1.1

COPY . /usr/local/share/nginx/src/app
RUN npm run build

FROM nginx:alpine
COPY --from=build /usr/local/share/nginx/src/app /usr/local/var/www
COPY nginx.dev.conf /usr/local/etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
